name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ secrets.MPKIT_URL }}
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Posify
      run: |
        mkdir -p app/views/{pages,layouts}
        echo "{{content_for_layout}}" > app/views/layouts/application.html
        cp -R build/static app/assets
        cp build/index.html app/views/pages
        sed -i -e 's/static/assets/g' app/views/pages/index.html
        mkdir -p app/schema
        echo "name: item\nproperties:\n  - name: title\n    type: string" > app/schema/item.yml
        
    - name: Install pos-cli and deploy
      run: |
        npm install -g @platformos/pos-cli
        pos-cli deploy
